name: CI

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 

    - name: Install dependencies
      run: |
        pip install -r fastapi/requirements.txt  
        pip install -r flask/requirements.txt    
        pip install -r mlflow/requirements.txt    

    - name: Run tests
      run: |
        pytest fastapi/test_app.py
        pytest flask/test_app.py
