name: CI

on:
  push:
    branches:
      - dev_traitement_dataset

jobs:
  runner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

  install_dependencies:
    needs: runner
    runs-on: ${{ needs.runner.outputs.runner-os }}

    steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: /github/home/.cache/pip
        key: pip-${{ needs.runner.outputs.runner-os }}-${{ hashFiles('fastapi/requirements.txt', 'flask/requirements.txt', 'mlflow/requirements.txt') }}
        restore-keys: |
          pip-${{ needs.runner.outputs.runner-os }}-

    - name: Install Dependencies
      run: |
        pip install -r fastapi/requirements.txt 
        pip install -r flask/requirements.txt    
        pip install -r mlflow/requirements.txt

  pytest_flask:
    needs: install_dependencies
    runs-on: ${{ needs.runner.outputs.runner-os }}

    steps:
    - name: Use Python from cache
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Run Flask Tests
      run: |
        cd ./flask
        pip install pytest
        pytest test_app.py

  pytest_fastapi:
    needs: install_dependencies
    runs-on: ${{ needs.runner.outputs.runner-os }}

    steps:
    - name: Use Python from cache
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Run FastAPI Tests
      run: |
        cd ./fastapi
        pip install pytest
        pytest test_app.py