name: CI

on:
  push:
    branches:
      - dev_traitement_dataset

jobs:
  clean_cache:
    runs-on: ubuntu-latest

    steps:
    - name: Clean Python cache
      run: |
        python -m pip cache purge

  install_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10  # Utilisez Python 3.10

    - name: Install Dependencies
      run: |
        pip install -r fastapi/requirements.txt 
        pip install -r flask/requirements.txt    
        pip install -r mlflow/requirements.txt

  pytest_flask:
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Change to Flask Directory
      run: cd ./flask

    - name: Run Flask Tests
      run: pytest test_app.py

  pytest_fastapi:
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Change to FastAPI Directory
      run: cd ./fastapi

    - name: Run FastAPI Tests
      run: pytest test_app.py