name: CI

on:
  push:
    branches:
      - dev_traitement_dataset

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Install Dependencies
      run: |
        pip install -r fastapi/requirements.txt 
        pip install -r flask/requirements.txt    
        pip install -r mlflow/requirements.txt
        pip install pytest

  pytest_flask:
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Change to Flask Directory
      run: cd ./flask

    - name: Run Flask Tests
      run: pytest test_app.py

  pytest_fastapi:
    needs: install_dependencies
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"

    - name: Change to FastAPI Directory
      run: cd ./fastapi

    - name: Run FastAPI Tests
      run: pytest test_app.py